CREATE TABLE SUPPLIER(
    SUP_NO VARCHAR(4) PRIMARY KEY,
    SUP_NAME VARCHAR(20),
    ITEM_SUPPLIED VARCHAR(20),
    ITEM_PRICE INT,
    CITY VARCHAR(20)
);

INSERT INTO SUPPLIER VALUES ('S1', 'Suresh', 'Keyboard', 400, 'Hyderabad');
INSERT INTO SUPPLIER VALUES ('S2', 'Kiran', 'Processor', 8000, 'Delhi');
INSERT INTO SUPPLIER VALUES ('S3', 'Mohan', 'Mouse', 350, 'Delhi');
INSERT INTO SUPPLIER VALUES ('S4', 'Ramesh', 'Processor', 9000, 'Banglore');
INSERT INTO SUPPLIER VALUES ('S5', 'Manish', 'Printer', 6000, 'Mumbai');
INSERT INTO SUPPLIER VALUES ('S6', 'Shrikanth', 'Processor', 8500, 'Chennai');

//Q1
SELECT SUP_NO, SUP_NAME
FROM SUPPLIER
WHERE SUP_NAME LIKE 'R%';

//Q2
SELECT SUP_NAME
FROM SUPPLIER
WHERE ITEM_SUPPLIED = 'Processor' AND CITY = 'Delhi';

//Q3
SELECT SUP_NAME
FROM SUPPLIER
WHERE ITEM_SUPPLIED = 
(
    SELECT ITEM_SUPPLIED
    FROM SUPPLIER
    WHERE SUP_NAME = 'Ramesh'
);

//Q4
UPDATE SUPPLIER
SET ITEM_PRICE = ITEM_PRICE + 200
WHERE ITEM_SUPPLIED = 'Keyboard';
  
//Q5
SELECT SUP_NO, SUP_NAME, ITEM_PRICE
FROM SUPPLIER
WHERE CITY = 'Delhi'
ORDER BY ITEM_PRICE;

//Q6
ALTER TABLE SUPPLIER
ADD CONTACT_NO CHAR(10);

//Q7
DELETE FROM SUPPLIER
WHERE ITEM_PRICE = 
(
    SELECT MIN(ITEM_PRICE)
    FROM SUPPLIER
);

//Q8
CREATE VIEW V1 AS
SELECT SUP_NO, SUP_NAME
FROM SUPPLIER

//Q9
SELECT ITEM_SUPPLIED, ITEM_PRICE FROM SUPPLIER
ORDER BY ITEM_PRICE DESC;

//Q10
SELECT * FROM SUPPLIER
WHERE ITEM_SUPPLIED NOT IN ('Keyboard', 'Processor');
